apiVersion: v1
kind: Service
metadata:
  name: cicd-s
  labels:
    app: cicd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: cicd